# NEW - Docker Compose for Development
version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: kaushalx-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2-alpine
    container_name: kaushalx-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ../apps/backend
      dockerfile: Dockerfile
    container_name: kaushalx-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/kaushalx?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - ../apps/backend:/app
      - /app/node_modules

volumes:
  mongo_data:
  redis_data: